apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: virtaus-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: virtaus-db
    spec:
      containers:
        - name: virtaus-db
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "docker"
            - name: POSTGRES_USER
              value: "docker"
            - name: POSTGRES_PASSWORD
              value: "docker"
---

apiVersion: v1
kind: Service
metadata:
  name: virtaus-db-service
spec:
  selector:
    app: virtaus-db
  ports:
    - protocol: TCP
      port: 5432
targetPort: 5432