apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-11-24T07:43:31Z
  generation: 1
  labels:
    run: virtaus-osr-finland
  name: virtaus-osr-finland
spec:
  replicas: 1
  selector:
    matchLabels:
      run: osr-finland
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: virtaus-osr-finland
    spec:
      containers:
      - image: kineticcookie/osr-finland:latest
        imagePullPolicy: Always
        name: virtaus-osr-finland
        ports:
        - containerPort: 5000
          protocol: TCP

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: virtaus-osr-finland-service
spec:
  selector:
    app: virtaus-osr-finland
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000