---
apiVersion: v1
kind: Pod
metadata:
  name: virtaus-frontend
  labels:
    app: virtaus-frontend
spec:
  containers:
    - name: virtaus-frontend
      image: kineticcookie/junction-frontend:2
      ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: virtaus-nav-service-service
spec:
  selector:
    app: virtaus-nav-service
  ports:
    - protocol: TCP
      port: 80
targetPort: 8080